// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.sukashiform.app

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FrameExtractorApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoInfo (
  val isValid: Boolean,
  val durationMs: Long,
  val width: Long,
  val height: Long,
  val rotationDegrees: Long? = null,
  val errorReason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoInfo {
      val isValid = pigeonVar_list[0] as Boolean
      val durationMs = pigeonVar_list[1] as Long
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val rotationDegrees = pigeonVar_list[4] as Long?
      val errorReason = pigeonVar_list[5] as String?
      return VideoInfo(isValid, durationMs, width, height, rotationDegrees, errorReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isValid,
      durationMs,
      width,
      height,
      rotationDegrees,
      errorReason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoInfo
    return FrameExtractorApiPigeonUtils.deepEquals(this.isValid, other.isValid) && FrameExtractorApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && FrameExtractorApiPigeonUtils.deepEquals(this.width, other.width) && FrameExtractorApiPigeonUtils.deepEquals(this.height, other.height) && FrameExtractorApiPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && FrameExtractorApiPigeonUtils.deepEquals(this.errorReason, other.errorReason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.isValid)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.width)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.height)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.errorReason)
    return result
  }
  override fun toString(): String {
    return "VideoInfo(isValid=$isValid, durationMs=$durationMs, width=$width, height=$height, rotationDegrees=$rotationDegrees, errorReason=$errorReason)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExtractRequest (
  val absoluteVideoPath: String,
  val absoluteOutputDir: String,
  val maxLongEdgePx: Long,
  val maxFrames: Long,
  val jpegQuality: Long,
  val rangeStartMs: Long? = null,
  val rangeEndMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractRequest {
      val absoluteVideoPath = pigeonVar_list[0] as String
      val absoluteOutputDir = pigeonVar_list[1] as String
      val maxLongEdgePx = pigeonVar_list[2] as Long
      val maxFrames = pigeonVar_list[3] as Long
      val jpegQuality = pigeonVar_list[4] as Long
      val rangeStartMs = pigeonVar_list[5] as Long?
      val rangeEndMs = pigeonVar_list[6] as Long?
      return ExtractRequest(absoluteVideoPath, absoluteOutputDir, maxLongEdgePx, maxFrames, jpegQuality, rangeStartMs, rangeEndMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      absoluteVideoPath,
      absoluteOutputDir,
      maxLongEdgePx,
      maxFrames,
      jpegQuality,
      rangeStartMs,
      rangeEndMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExtractRequest
    return FrameExtractorApiPigeonUtils.deepEquals(this.absoluteVideoPath, other.absoluteVideoPath) && FrameExtractorApiPigeonUtils.deepEquals(this.absoluteOutputDir, other.absoluteOutputDir) && FrameExtractorApiPigeonUtils.deepEquals(this.maxLongEdgePx, other.maxLongEdgePx) && FrameExtractorApiPigeonUtils.deepEquals(this.maxFrames, other.maxFrames) && FrameExtractorApiPigeonUtils.deepEquals(this.jpegQuality, other.jpegQuality) && FrameExtractorApiPigeonUtils.deepEquals(this.rangeStartMs, other.rangeStartMs) && FrameExtractorApiPigeonUtils.deepEquals(this.rangeEndMs, other.rangeEndMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.absoluteVideoPath)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.absoluteOutputDir)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.maxLongEdgePx)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.maxFrames)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.jpegQuality)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.rangeStartMs)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.rangeEndMs)
    return result
  }
  override fun toString(): String {
    return "ExtractRequest(absoluteVideoPath=$absoluteVideoPath, absoluteOutputDir=$absoluteOutputDir, maxLongEdgePx=$maxLongEdgePx, maxFrames=$maxFrames, jpegQuality=$jpegQuality, rangeStartMs=$rangeStartMs, rangeEndMs=$rangeEndMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExtractResult (
  val isComplete: Boolean,
  val frameCount: Long,
  val sourceDurationMs: Long,
  val sourceFps: Double,
  val errorReason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExtractResult {
      val isComplete = pigeonVar_list[0] as Boolean
      val frameCount = pigeonVar_list[1] as Long
      val sourceDurationMs = pigeonVar_list[2] as Long
      val sourceFps = pigeonVar_list[3] as Double
      val errorReason = pigeonVar_list[4] as String?
      return ExtractResult(isComplete, frameCount, sourceDurationMs, sourceFps, errorReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isComplete,
      frameCount,
      sourceDurationMs,
      sourceFps,
      errorReason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExtractResult
    return FrameExtractorApiPigeonUtils.deepEquals(this.isComplete, other.isComplete) && FrameExtractorApiPigeonUtils.deepEquals(this.frameCount, other.frameCount) && FrameExtractorApiPigeonUtils.deepEquals(this.sourceDurationMs, other.sourceDurationMs) && FrameExtractorApiPigeonUtils.deepEquals(this.sourceFps, other.sourceFps) && FrameExtractorApiPigeonUtils.deepEquals(this.errorReason, other.errorReason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.isComplete)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.frameCount)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.sourceDurationMs)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.sourceFps)
    result = 31 * result + FrameExtractorApiPigeonUtils.deepHash(this.errorReason)
    return result
  }
  override fun toString(): String {
    return "ExtractResult(isComplete=$isComplete, frameCount=$frameCount, sourceDurationMs=$sourceDurationMs, sourceFps=$sourceFps, errorReason=$errorReason)"
  }
}
private open class FrameExtractorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExtractResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VideoInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ExtractRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ExtractResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FrameExtractorApi {
  fun probe(absoluteVideoPath: String, callback: (Result<VideoInfo>) -> Unit)
  fun generateThumbnail(absoluteVideoPath: String, absoluteOutputPath: String, maxLongEdgePx: Long, callback: (Result<String>) -> Unit)
  fun extractFrames(taskId: String, request: ExtractRequest, callback: (Result<ExtractResult>) -> Unit)
  fun cancelExtraction(taskId: String)
  fun isGallerySaveSupported(): Boolean
  fun saveVideoToGallery(absoluteVideoPath: String, callback: (Result<Unit>) -> Unit)
  fun setVolumeKeyCaptureEnabled(enabled: Boolean)

  companion object {
    /** The codec used by FrameExtractorApi. */
    val codec: MessageCodec<Any?> by lazy {
      FrameExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `FrameExtractorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FrameExtractorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.probe$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absoluteVideoPathArg = args[0] as String
            api.probe(absoluteVideoPathArg) { result: Result<VideoInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FrameExtractorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FrameExtractorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.generateThumbnail$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absoluteVideoPathArg = args[0] as String
            val absoluteOutputPathArg = args[1] as String
            val maxLongEdgePxArg = args[2] as Long
            api.generateThumbnail(absoluteVideoPathArg, absoluteOutputPathArg, maxLongEdgePxArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FrameExtractorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FrameExtractorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.extractFrames$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val requestArg = args[1] as ExtractRequest
            api.extractFrames(taskIdArg, requestArg) { result: Result<ExtractResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FrameExtractorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FrameExtractorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.cancelExtraction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val taskIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelExtraction(taskIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              FrameExtractorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.isGallerySaveSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isGallerySaveSupported())
            } catch (exception: Throwable) {
              FrameExtractorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.saveVideoToGallery$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val absoluteVideoPathArg = args[0] as String
            api.saveVideoToGallery(absoluteVideoPathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FrameExtractorApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(FrameExtractorApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.setVolumeKeyCaptureEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setVolumeKeyCaptureEnabled(enabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              FrameExtractorApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FrameExtractionProgressApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FrameExtractionProgressApi. */
    val codec: MessageCodec<Any?> by lazy {
      FrameExtractorApiPigeonCodec()
    }
  }
  fun onProgress(taskIdArg: String, completedFramesArg: Long, totalFramesArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.sukashi_form.FrameExtractionProgressApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(taskIdArg, completedFramesArg, totalFramesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(FrameExtractorApiPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class VolumeKeyApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by VolumeKeyApi. */
    val codec: MessageCodec<Any?> by lazy {
      FrameExtractorApiPigeonCodec()
    }
  }
  fun onVolumeKeyPressed(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.sukashi_form.VolumeKeyApi.onVolumeKeyPressed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(FrameExtractorApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
