// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum FrameExtractorApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct VideoInfo: Hashable, CustomStringConvertible {
  var isValid: Bool
  var durationMs: Int64
  var width: Int64
  var height: Int64
  var rotationDegrees: Int64? = nil
  var errorReason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoInfo? {
    let isValid = pigeonVar_list[0] as! Bool
    let durationMs = pigeonVar_list[1] as! Int64
    let width = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! Int64
    let rotationDegrees: Int64? = nilOrValue(pigeonVar_list[4])
    let errorReason: String? = nilOrValue(pigeonVar_list[5])

    return VideoInfo(
      isValid: isValid,
      durationMs: durationMs,
      width: width,
      height: height,
      rotationDegrees: rotationDegrees,
      errorReason: errorReason
    )
  }
  func toList() -> [Any?] {
    return [
      isValid,
      durationMs,
      width,
      height,
      rotationDegrees,
      errorReason,
    ]
  }
  static func == (lhs: VideoInfo, rhs: VideoInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FrameExtractorApiPigeonInternal.deepEquals(lhs.isValid, rhs.isValid) && FrameExtractorApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && FrameExtractorApiPigeonInternal.deepEquals(lhs.width, rhs.width) && FrameExtractorApiPigeonInternal.deepEquals(lhs.height, rhs.height) && FrameExtractorApiPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && FrameExtractorApiPigeonInternal.deepEquals(lhs.errorReason, rhs.errorReason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoInfo")
    FrameExtractorApiPigeonInternal.deepHash(value: isValid, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: errorReason, hasher: &hasher)
  }

  public var description: String {
    return "VideoInfo(isValid: \(String(describing: isValid)), durationMs: \(String(describing: durationMs)), width: \(String(describing: width)), height: \(String(describing: height)), rotationDegrees: \(String(describing: rotationDegrees)), errorReason: \(String(describing: errorReason)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExtractRequest: Hashable, CustomStringConvertible {
  var absoluteVideoPath: String
  var absoluteOutputDir: String
  var maxLongEdgePx: Int64
  var maxFrames: Int64
  var jpegQuality: Int64
  var rangeStartMs: Int64? = nil
  var rangeEndMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtractRequest? {
    let absoluteVideoPath = pigeonVar_list[0] as! String
    let absoluteOutputDir = pigeonVar_list[1] as! String
    let maxLongEdgePx = pigeonVar_list[2] as! Int64
    let maxFrames = pigeonVar_list[3] as! Int64
    let jpegQuality = pigeonVar_list[4] as! Int64
    let rangeStartMs: Int64? = nilOrValue(pigeonVar_list[5])
    let rangeEndMs: Int64? = nilOrValue(pigeonVar_list[6])

    return ExtractRequest(
      absoluteVideoPath: absoluteVideoPath,
      absoluteOutputDir: absoluteOutputDir,
      maxLongEdgePx: maxLongEdgePx,
      maxFrames: maxFrames,
      jpegQuality: jpegQuality,
      rangeStartMs: rangeStartMs,
      rangeEndMs: rangeEndMs
    )
  }
  func toList() -> [Any?] {
    return [
      absoluteVideoPath,
      absoluteOutputDir,
      maxLongEdgePx,
      maxFrames,
      jpegQuality,
      rangeStartMs,
      rangeEndMs,
    ]
  }
  static func == (lhs: ExtractRequest, rhs: ExtractRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FrameExtractorApiPigeonInternal.deepEquals(lhs.absoluteVideoPath, rhs.absoluteVideoPath) && FrameExtractorApiPigeonInternal.deepEquals(lhs.absoluteOutputDir, rhs.absoluteOutputDir) && FrameExtractorApiPigeonInternal.deepEquals(lhs.maxLongEdgePx, rhs.maxLongEdgePx) && FrameExtractorApiPigeonInternal.deepEquals(lhs.maxFrames, rhs.maxFrames) && FrameExtractorApiPigeonInternal.deepEquals(lhs.jpegQuality, rhs.jpegQuality) && FrameExtractorApiPigeonInternal.deepEquals(lhs.rangeStartMs, rhs.rangeStartMs) && FrameExtractorApiPigeonInternal.deepEquals(lhs.rangeEndMs, rhs.rangeEndMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExtractRequest")
    FrameExtractorApiPigeonInternal.deepHash(value: absoluteVideoPath, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: absoluteOutputDir, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: maxLongEdgePx, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: maxFrames, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: jpegQuality, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: rangeStartMs, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: rangeEndMs, hasher: &hasher)
  }

  public var description: String {
    return "ExtractRequest(absoluteVideoPath: \(String(describing: absoluteVideoPath)), absoluteOutputDir: \(String(describing: absoluteOutputDir)), maxLongEdgePx: \(String(describing: maxLongEdgePx)), maxFrames: \(String(describing: maxFrames)), jpegQuality: \(String(describing: jpegQuality)), rangeStartMs: \(String(describing: rangeStartMs)), rangeEndMs: \(String(describing: rangeEndMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePoseLandmark: Hashable, CustomStringConvertible {
  var joint: String
  var x: Double
  var y: Double
  var visibility: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePoseLandmark? {
    let joint = pigeonVar_list[0] as! String
    let x = pigeonVar_list[1] as! Double
    let y = pigeonVar_list[2] as! Double
    let visibility = pigeonVar_list[3] as! Double

    return NativePoseLandmark(
      joint: joint,
      x: x,
      y: y,
      visibility: visibility
    )
  }
  func toList() -> [Any?] {
    return [
      joint,
      x,
      y,
      visibility,
    ]
  }
  static func == (lhs: NativePoseLandmark, rhs: NativePoseLandmark) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FrameExtractorApiPigeonInternal.deepEquals(lhs.joint, rhs.joint) && FrameExtractorApiPigeonInternal.deepEquals(lhs.x, rhs.x) && FrameExtractorApiPigeonInternal.deepEquals(lhs.y, rhs.y) && FrameExtractorApiPigeonInternal.deepEquals(lhs.visibility, rhs.visibility)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePoseLandmark")
    FrameExtractorApiPigeonInternal.deepHash(value: joint, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: visibility, hasher: &hasher)
  }

  public var description: String {
    return "NativePoseLandmark(joint: \(String(describing: joint)), x: \(String(describing: x)), y: \(String(describing: y)), visibility: \(String(describing: visibility)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePoseResult: Hashable, CustomStringConvertible {
  var found: Bool
  var imageWidth: Double
  var imageHeight: Double
  var landmarks: [NativePoseLandmark]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePoseResult? {
    let found = pigeonVar_list[0] as! Bool
    let imageWidth = pigeonVar_list[1] as! Double
    let imageHeight = pigeonVar_list[2] as! Double
    let landmarks = pigeonVar_list[3] as! [NativePoseLandmark]

    return NativePoseResult(
      found: found,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      landmarks: landmarks
    )
  }
  func toList() -> [Any?] {
    return [
      found,
      imageWidth,
      imageHeight,
      landmarks,
    ]
  }
  static func == (lhs: NativePoseResult, rhs: NativePoseResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FrameExtractorApiPigeonInternal.deepEquals(lhs.found, rhs.found) && FrameExtractorApiPigeonInternal.deepEquals(lhs.imageWidth, rhs.imageWidth) && FrameExtractorApiPigeonInternal.deepEquals(lhs.imageHeight, rhs.imageHeight) && FrameExtractorApiPigeonInternal.deepEquals(lhs.landmarks, rhs.landmarks)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePoseResult")
    FrameExtractorApiPigeonInternal.deepHash(value: found, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: imageWidth, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: imageHeight, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: landmarks, hasher: &hasher)
  }

  public var description: String {
    return "NativePoseResult(found: \(String(describing: found)), imageWidth: \(String(describing: imageWidth)), imageHeight: \(String(describing: imageHeight)), landmarks: \(String(describing: landmarks)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExtractResult: Hashable, CustomStringConvertible {
  var isComplete: Bool
  var frameCount: Int64
  var sourceDurationMs: Int64
  var sourceFps: Double
  var errorReason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExtractResult? {
    let isComplete = pigeonVar_list[0] as! Bool
    let frameCount = pigeonVar_list[1] as! Int64
    let sourceDurationMs = pigeonVar_list[2] as! Int64
    let sourceFps = pigeonVar_list[3] as! Double
    let errorReason: String? = nilOrValue(pigeonVar_list[4])

    return ExtractResult(
      isComplete: isComplete,
      frameCount: frameCount,
      sourceDurationMs: sourceDurationMs,
      sourceFps: sourceFps,
      errorReason: errorReason
    )
  }
  func toList() -> [Any?] {
    return [
      isComplete,
      frameCount,
      sourceDurationMs,
      sourceFps,
      errorReason,
    ]
  }
  static func == (lhs: ExtractResult, rhs: ExtractResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FrameExtractorApiPigeonInternal.deepEquals(lhs.isComplete, rhs.isComplete) && FrameExtractorApiPigeonInternal.deepEquals(lhs.frameCount, rhs.frameCount) && FrameExtractorApiPigeonInternal.deepEquals(lhs.sourceDurationMs, rhs.sourceDurationMs) && FrameExtractorApiPigeonInternal.deepEquals(lhs.sourceFps, rhs.sourceFps) && FrameExtractorApiPigeonInternal.deepEquals(lhs.errorReason, rhs.errorReason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExtractResult")
    FrameExtractorApiPigeonInternal.deepHash(value: isComplete, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: frameCount, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: sourceDurationMs, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: sourceFps, hasher: &hasher)
    FrameExtractorApiPigeonInternal.deepHash(value: errorReason, hasher: &hasher)
  }

  public var description: String {
    return "ExtractResult(isComplete: \(String(describing: isComplete)), frameCount: \(String(describing: frameCount)), sourceDurationMs: \(String(describing: sourceDurationMs)), sourceFps: \(String(describing: sourceFps)), errorReason: \(String(describing: errorReason)))"
  }
}

private class FrameExtractorApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VideoInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return ExtractRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return NativePoseLandmark.fromList(self.readValue() as! [Any?])
    case 132:
      return NativePoseResult.fromList(self.readValue() as! [Any?])
    case 133:
      return ExtractResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FrameExtractorApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VideoInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ExtractRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativePoseLandmark {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativePoseResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ExtractResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FrameExtractorApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FrameExtractorApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FrameExtractorApiPigeonCodecWriter(data: data)
  }
}

class FrameExtractorApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FrameExtractorApiPigeonCodec(readerWriter: FrameExtractorApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FrameExtractorApi {
  func probe(absoluteVideoPath: String, completion: @escaping (Result<VideoInfo, Error>) -> Void)
  func generateThumbnail(absoluteVideoPath: String, absoluteOutputPath: String, maxLongEdgePx: Int64, completion: @escaping (Result<String, Error>) -> Void)
  func extractFrames(taskId: String, request: ExtractRequest, completion: @escaping (Result<ExtractResult, Error>) -> Void)
  func cancelExtraction(taskId: String) throws
  func isGallerySaveSupported() throws -> Bool
  func saveVideoToGallery(absoluteVideoPath: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setVolumeKeyCaptureEnabled(enabled: Bool) throws
  func detectPose(absoluteImagePath: String, completion: @escaping (Result<NativePoseResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FrameExtractorApiSetup {
  static var codec: FlutterStandardMessageCodec { FrameExtractorApiPigeonCodec.shared }
  /// Sets up an instance of `FrameExtractorApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FrameExtractorApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let probeChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let absoluteVideoPathArg = args[0] as! String
        api.probe(absoluteVideoPath: absoluteVideoPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    let generateThumbnailChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.generateThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.generateThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      generateThumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let absoluteVideoPathArg = args[0] as! String
        let absoluteOutputPathArg = args[1] as! String
        let maxLongEdgePxArg = args[2] as! Int64
        api.generateThumbnail(absoluteVideoPath: absoluteVideoPathArg, absoluteOutputPath: absoluteOutputPathArg, maxLongEdgePx: maxLongEdgePxArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateThumbnailChannel.setMessageHandler(nil)
    }
    let extractFramesChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.extractFrames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.extractFrames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      extractFramesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        let requestArg = args[1] as! ExtractRequest
        api.extractFrames(taskId: taskIdArg, request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      extractFramesChannel.setMessageHandler(nil)
    }
    let cancelExtractionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.cancelExtraction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelExtractionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskIdArg = args[0] as! String
        do {
          try api.cancelExtraction(taskId: taskIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelExtractionChannel.setMessageHandler(nil)
    }
    let isGallerySaveSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.isGallerySaveSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isGallerySaveSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isGallerySaveSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isGallerySaveSupportedChannel.setMessageHandler(nil)
    }
    let saveVideoToGalleryChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.saveVideoToGallery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.saveVideoToGallery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      saveVideoToGalleryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let absoluteVideoPathArg = args[0] as! String
        api.saveVideoToGallery(absoluteVideoPath: absoluteVideoPathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveVideoToGalleryChannel.setMessageHandler(nil)
    }
    let setVolumeKeyCaptureEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.setVolumeKeyCaptureEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeKeyCaptureEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setVolumeKeyCaptureEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeKeyCaptureEnabledChannel.setMessageHandler(nil)
    }
    let detectPoseChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.detectPose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sukashi_form.FrameExtractorApi.detectPose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      detectPoseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let absoluteImagePathArg = args[0] as! String
        api.detectPose(absoluteImagePath: absoluteImagePathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      detectPoseChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FrameExtractionProgressApiProtocol {
  func onProgress(taskId taskIdArg: String, completedFrames completedFramesArg: Int64, totalFrames totalFramesArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class FrameExtractionProgressApi: FrameExtractionProgressApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FrameExtractorApiPigeonCodec {
    return FrameExtractorApiPigeonCodec.shared
  }
  func onProgress(taskId taskIdArg: String, completedFrames completedFramesArg: Int64, totalFrames totalFramesArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sukashi_form.FrameExtractionProgressApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([taskIdArg, completedFramesArg, totalFramesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol VolumeKeyApiProtocol {
  func onVolumeKeyPressed(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class VolumeKeyApi: VolumeKeyApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FrameExtractorApiPigeonCodec {
    return FrameExtractorApiPigeonCodec.shared
  }
  func onVolumeKeyPressed(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.sukashi_form.VolumeKeyApi.onVolumeKeyPressed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
