// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class VideoInfo {
  VideoInfo({
    required this.isValid,
    required this.durationMs,
    required this.width,
    required this.height,
    this.rotationDegrees,
    this.errorReason,
  });

  bool isValid;

  int durationMs;

  int width;

  int height;

  int? rotationDegrees;

  String? errorReason;

  List<Object?> _toList() {
    return <Object?>[
      isValid,
      durationMs,
      width,
      height,
      rotationDegrees,
      errorReason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VideoInfo decode(Object result) {
    result as List<Object?>;
    return VideoInfo(
      isValid: result[0]! as bool,
      durationMs: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
      rotationDegrees: result[4] as int?,
      errorReason: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isValid, other.isValid) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(rotationDegrees, other.rotationDegrees) &&
        _deepEquals(errorReason, other.errorReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoInfo(isValid: $isValid, durationMs: $durationMs, width: $width, height: $height, rotationDegrees: $rotationDegrees, errorReason: $errorReason)';
  }
}

class ExtractRequest {
  ExtractRequest({
    required this.absoluteVideoPath,
    required this.absoluteOutputDir,
    required this.maxLongEdgePx,
    required this.maxFrames,
    required this.jpegQuality,
    this.rangeStartMs,
    this.rangeEndMs,
  });

  String absoluteVideoPath;

  String absoluteOutputDir;

  int maxLongEdgePx;

  int maxFrames;

  int jpegQuality;

  int? rangeStartMs;

  int? rangeEndMs;

  List<Object?> _toList() {
    return <Object?>[
      absoluteVideoPath,
      absoluteOutputDir,
      maxLongEdgePx,
      maxFrames,
      jpegQuality,
      rangeStartMs,
      rangeEndMs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExtractRequest decode(Object result) {
    result as List<Object?>;
    return ExtractRequest(
      absoluteVideoPath: result[0]! as String,
      absoluteOutputDir: result[1]! as String,
      maxLongEdgePx: result[2]! as int,
      maxFrames: result[3]! as int,
      jpegQuality: result[4]! as int,
      rangeStartMs: result[5] as int?,
      rangeEndMs: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtractRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(absoluteVideoPath, other.absoluteVideoPath) &&
        _deepEquals(absoluteOutputDir, other.absoluteOutputDir) &&
        _deepEquals(maxLongEdgePx, other.maxLongEdgePx) &&
        _deepEquals(maxFrames, other.maxFrames) &&
        _deepEquals(jpegQuality, other.jpegQuality) &&
        _deepEquals(rangeStartMs, other.rangeStartMs) &&
        _deepEquals(rangeEndMs, other.rangeEndMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtractRequest(absoluteVideoPath: $absoluteVideoPath, absoluteOutputDir: $absoluteOutputDir, maxLongEdgePx: $maxLongEdgePx, maxFrames: $maxFrames, jpegQuality: $jpegQuality, rangeStartMs: $rangeStartMs, rangeEndMs: $rangeEndMs)';
  }
}

class ExtractResult {
  ExtractResult({
    required this.isComplete,
    required this.frameCount,
    required this.sourceDurationMs,
    required this.sourceFps,
    this.errorReason,
  });

  bool isComplete;

  int frameCount;

  int sourceDurationMs;

  double sourceFps;

  String? errorReason;

  List<Object?> _toList() {
    return <Object?>[
      isComplete,
      frameCount,
      sourceDurationMs,
      sourceFps,
      errorReason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExtractResult decode(Object result) {
    result as List<Object?>;
    return ExtractResult(
      isComplete: result[0]! as bool,
      frameCount: result[1]! as int,
      sourceDurationMs: result[2]! as int,
      sourceFps: result[3]! as double,
      errorReason: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExtractResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isComplete, other.isComplete) &&
        _deepEquals(frameCount, other.frameCount) &&
        _deepEquals(sourceDurationMs, other.sourceDurationMs) &&
        _deepEquals(sourceFps, other.sourceFps) &&
        _deepEquals(errorReason, other.errorReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExtractResult(isComplete: $isComplete, frameCount: $frameCount, sourceDurationMs: $sourceDurationMs, sourceFps: $sourceFps, errorReason: $errorReason)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VideoInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ExtractRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ExtractResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return VideoInfo.decode(readValue(buffer)!);
      case 130:
        return ExtractRequest.decode(readValue(buffer)!);
      case 131:
        return ExtractResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FrameExtractorApi {
  /// Constructor for [FrameExtractorApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FrameExtractorApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<VideoInfo> probe(String absoluteVideoPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absoluteVideoPath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VideoInfo;
  }

  Future<String> generateThumbnail(
    String absoluteVideoPath,
    String absoluteOutputPath,
    int maxLongEdgePx,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.generateThumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absoluteVideoPath, absoluteOutputPath, maxLongEdgePx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<ExtractResult> extractFrames(
    String taskId,
    ExtractRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.extractFrames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[taskId, request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExtractResult;
  }

  Future<void> cancelExtraction(String taskId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.cancelExtraction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[taskId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> isGallerySaveSupported() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.isGallerySaveSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> saveVideoToGallery(String absoluteVideoPath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.saveVideoToGallery$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[absoluteVideoPath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVolumeKeyCaptureEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.sukashi_form.FrameExtractorApi.setVolumeKeyCaptureEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class FrameExtractionProgressApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgress(String taskId, int completedFrames, int totalFrames);

  static void setUp(
    FrameExtractionProgressApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sukashi_form.FrameExtractionProgressApi.onProgress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_taskId = args[0]! as String;
          final int arg_completedFrames = args[1]! as int;
          final int arg_totalFrames = args[2]! as int;
          try {
            api.onProgress(arg_taskId, arg_completedFrames, arg_totalFrames);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

abstract class VolumeKeyApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onVolumeKeyPressed();

  static void setUp(
    VolumeKeyApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sukashi_form.VolumeKeyApi.onVolumeKeyPressed$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onVolumeKeyPressed();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
